"""End-to-end matrix coverage: every row of the #75 status-code
matrix exercised through every fallback operation via the *real*
``huggingface_hub`` API (``hf_hub_download``, ``HfApi.model_info``,
``HfApi.list_repo_files``, ``HfApi.get_paths_info``,
``HfApi.file_exists``).

Why this is exhaustive rather than a unit-test layer:

- The classifier itself is unit-tested in ``test_utils.py``.
- The per-op binding logic is unit-tested in ``test_operations.py``.
- The interop layer (driving ``hf_raise_for_status`` directly with
  rehydrated FastAPI responses) is in ``test_hf_hub_interop.py``.

What's left, and what *this* file proves: that a real
``huggingface_hub`` client talking to a real KohakuHub uvicorn
process — which in turn talks to a real upstream uvicorn (the
parametric scenario mock) — observes the right exception class /
download success for every cell of the matrix.

The test set is generated by parametrizing one test per
(operation × matrix-row); each row's expected outcome is encoded
once and shared across operations. ``ALL_SCENARIOS`` is the master
list — adding a row here means every operation gets covered for it.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest
from huggingface_hub import HfApi, hf_hub_download

from test.kohakuhub.support.live_server import start_live_server, stop_live_server
from test.kohakuhub.support.scenario_hf_server import (
    OK_BODY,
    OK_INFO_JSON,
    OK_TREE_JSON,
    build_scenario_hf_app,
)


def _hf_error(name: str):
    """Resolve hf_hub exception class across the version matrix.

    - 0.20.x: only ``huggingface_hub.utils.<Name>`` is importable
    - 0.30+ : ``huggingface_hub.errors.<Name>`` is canonical
    """
    try:
        mod = __import__("huggingface_hub.errors", fromlist=[name])
        return getattr(mod, name)
    except (ImportError, AttributeError):
        pass
    mod = __import__("huggingface_hub.utils", fromlist=[name])
    return getattr(mod, name)


@pytest.fixture(scope="module")
def scenario_mock_url():
    """Single uvicorn for all matrix tests in the module — the mock
    is stateless (scenarios are encoded in the URL path), so no
    cross-test pollution."""
    handle = start_live_server(build_scenario_hf_app())
    try:
        yield handle.base_url
    finally:
        stop_live_server(handle)


@pytest.fixture
def configure_fallback(backend_test_state, scenario_mock_url):
    """Per-test helper. ``configure(*scenario_names)`` sets the khub
    fallback chain to one source per scenario name; each source's
    URL ends in ``/scenario/{name}`` so the mock dispatches per the
    matrix row.

    The fallback cache is cleared on entry and exit; the previous
    config is restored after the test.
    """
    cfg = backend_test_state.modules.config_module.cfg
    old_sources = list(cfg.fallback.sources)
    old_enabled = cfg.fallback.enabled
    cfg.fallback.enabled = True

    def _configure(*scenario_names: str):
        cfg.fallback.sources = [
            {
                "url": f"{scenario_mock_url}/scenario/{name}",
                "name": f"Mock-{name}-{i}",
                "source_type": "huggingface",
                "priority": i + 1,
            }
            for i, name in enumerate(scenario_names)
        ]
        backend_test_state.modules.fallback_cache_module.get_cache().clear()

    backend_test_state.modules.fallback_cache_module.get_cache().clear()
    try:
        yield _configure
    finally:
        cfg.fallback.sources = old_sources
        cfg.fallback.enabled = old_enabled
        backend_test_state.modules.fallback_cache_module.get_cache().clear()


# ---------------------------------------------------------------------------
# Matrix master list. One row = one upstream-response shape from #75.
#
# ``expected`` is one of:
#   - ``"success"`` → the operation completes (download bytes / metadata
#     returned). Per-op success assertions live in the test bodies.
#   - exception class name (resolved via ``_hf_error``) → the operation
#     must raise that specific class on the hf_hub client.
#
# Per-op overrides where the matrix outcome differs by operation are
# kept in the per-op MATRIX list right above each test.
# ---------------------------------------------------------------------------


# --- Resolve flow (hf_hub_download) ---
#
# ``hf_hub_download`` has a head-call-error wrapper at
# ``huggingface_hub/file_download.py:_raise_on_head_call_error`` that
# *only* propagates these specific exception classes (plus 401-status
# generic errors):
#
#   RevisionNotFoundError, RemoteEntryNotFoundError → propagate
#   GatedRepoError, RepositoryNotFoundError         → propagate
#   401-status HfHubHTTPError                       → propagate
#   anything else (DisabledRepoError, 403, 5xx)     → wrap as
#                                                     LocalEntryNotFoundError
#
# So the matrix below differs from the raw classifier matrix in three
# rows: ``disabled``, ``403_bare``, ``503`` end up as
# ``LocalEntryNotFoundError`` even though the upstream/aggregate
# response is a DisabledRepo / 403 / 502 respectively. Other
# operations (model_info, list_repo_files, get_paths_info) call
# ``hf_raise_for_status`` directly without the wrapper and see the
# classifier-natural exception classes — see INFO_MATRIX etc. below.
#
# 5xx is omitted from this matrix because hf_hub_download retries
# 5xx 5 times with exponential backoff (~30s); the unit-layer tests
# in test_operations.py already cover that the aggregate is 502 and
# test_hf_hub_interop.py proves the classifier path is correct.
RESOLVE_MATRIX = [
    pytest.param("200_ok",                "success",                  id="200-ok"),
    # ``307_canonical_redirect`` intentionally absent: HF routes
    # ``/{name}/resolve/...`` directly to the canonical-named
    # storage rather than emitting a 307. Verified 2026-04-30 against
    # ``HEAD /bert-base-uncased/resolve/main/config.json`` — the
    # response is 307 to the resolve-cache CDN (a different shape,
    # covered by ``307_resolve_cache``), not to a canonical-name
    # path. Canonical redirect lives only on the API surface
    # (info / tree / paths-info).
    pytest.param("307_resolve_cache",     "success",                  id="307-resolve-cache"),
    pytest.param("404_entry_not_found",   "EntryNotFoundError",       id="404-entry-not-found-PROPAGATE"),
    pytest.param("404_revision_not_found","RevisionNotFoundError",    id="404-revision-not-found-PROPAGATE"),
    # ``disabled`` now routes to TRY_NEXT_SOURCE per the updated
    # policy (a moderation takedown on one source doesn't bind the
    # chain — sibling sources may still serve). With a single source
    # the aggregate preserves the disabled marker; hf_hub raises
    # DisabledRepoError, which hf_hub_download's wrapper does NOT
    # propagate (it's not in its allowlist), so it surfaces as
    # LocalEntryNotFoundError end-to-end.
    pytest.param("disabled",              "LocalEntryNotFoundError",  id="disabled-aggregate-wrapped"),
    pytest.param("404_repo_not_found",    "RepositoryNotFoundError",  id="404-repo-not-found-aggregate"),
    pytest.param("401_gated",             "GatedRepoError",           id="401-gated-aggregate"),
    pytest.param("403_gated",             "GatedRepoError",           id="403-gated-aggregate"),
    pytest.param("401_bare_anti_enum",    "RepositoryNotFoundError",  id="401-bare-anti-enum-aggregate"),
    pytest.param("401_bare_invalid_creds","RepositoryNotFoundError",  id="401-bare-invalid-creds-aggregate"),
    pytest.param("403_bare",              "LocalEntryNotFoundError",  id="403-bare-aggregate-wrapped"),
    pytest.param("404_bare",              "EntryNotFoundError",       id="404-bare-aggregate-scope-file"),
    # ``503`` omitted: hf_hub_download retries 5xx with backoff
    # (~30s/test). Aggregate-to-502 path is covered by
    # test_operations.py and test_hf_hub_interop.py instead.
]


def _maybe_skip_disabled(expected: str) -> None:
    if expected == "DisabledRepoError":
        try:
            _hf_error("DisabledRepoError")
        except (AttributeError, ImportError):
            pytest.skip("DisabledRepoError not exported by this hf_hub version")


@pytest.mark.parametrize("scenario,expected", RESOLVE_MATRIX)
def test_resolve_matrix_via_hf_hub_download(
    scenario, expected,
    live_server_url, hf_api_token, configure_fallback, tmp_path,
):
    """Drive ``hf_hub_download`` against khub for every matrix row.

    On ``"success"`` the downloaded bytes must equal ``OK_BODY`` (no
    proxying corruption). On error rows, the named exception must be
    raised — matching what a hf_hub client talking to HF directly
    would see for the same underlying upstream shape.
    """
    _maybe_skip_disabled(expected)
    configure_fallback(scenario)

    def _run():
        return hf_hub_download(
            repo_id="owner/scenario-repo",
            filename="config.json",
            endpoint=live_server_url,
            token=hf_api_token,
            cache_dir=str(tmp_path),
        )

    if expected == "success":
        path = asyncio.run(asyncio.to_thread(_run))
        assert Path(path).read_bytes() == OK_BODY
    else:
        Exc = _hf_error(expected)
        with pytest.raises(Exc):
            asyncio.run(asyncio.to_thread(_run))


# --- Info flow (HfApi.model_info) ---
#
# Differences from resolve:
# - aggregate scope is "repo" (info is repo-level), so all-bare-404
#   maps to RepoNotFound rather than EntryNotFound.
# - 307_resolve_cache is a resolve-only HF response shape; we skip
#   it for info (no canonical info redirect with X-Linked-Size).
INFO_MATRIX = [
    pytest.param("200_ok",                "success",                  id="200-ok"),
    pytest.param("307_canonical_redirect","success",                  id="307-canonical-redirect"),
    pytest.param("404_entry_not_found",   "EntryNotFoundError",       id="404-entry-not-found-PROPAGATE-info-edge-case"),
    pytest.param("404_revision_not_found","RevisionNotFoundError",    id="404-revision-not-found-PROPAGATE-info-edge-case"),
    pytest.param("disabled",              "DisabledRepoError",        id="disabled-PROPAGATE"),
    pytest.param("404_repo_not_found",    "RepositoryNotFoundError",  id="404-repo-not-found-aggregate"),
    pytest.param("401_gated",             "GatedRepoError",           id="401-gated-aggregate"),
    pytest.param("403_gated",             "GatedRepoError",           id="403-gated-aggregate"),
    pytest.param("401_bare_anti_enum",    "RepositoryNotFoundError",  id="401-bare-anti-enum-aggregate"),
    pytest.param("401_bare_invalid_creds","RepositoryNotFoundError",  id="401-bare-invalid-creds-aggregate"),
    pytest.param("403_bare",              "HfHubHTTPError",           id="403-bare-aggregate"),
    # bare 404 on a repo-level op aggregates to scope="repo" → RepoNotFound.
    pytest.param("404_bare",              "RepositoryNotFoundError",  id="404-bare-aggregate-scope-repo"),
    pytest.param("503",                   "HfHubHTTPError",           id="503-aggregate-502"),
]


@pytest.mark.parametrize("scenario,expected", INFO_MATRIX)
def test_info_matrix_via_hf_api_model_info(
    scenario, expected,
    live_server_url, hf_api_token, configure_fallback,
):
    """Drive ``HfApi.model_info`` against khub for every matrix row."""
    _maybe_skip_disabled(expected)
    configure_fallback(scenario)
    api = HfApi(endpoint=live_server_url, token=hf_api_token)

    def _run():
        return api.model_info("owner/scenario-repo")

    if expected == "success":
        info = asyncio.run(asyncio.to_thread(_run))
        # HfApi parses our scenario-mock JSON into ModelInfo. The id
        # field survives that translation across all hf_hub versions.
        assert getattr(info, "id", None) == OK_INFO_JSON["id"]
    else:
        Exc = _hf_error(expected)
        with pytest.raises(Exc):
            asyncio.run(asyncio.to_thread(_run))


# --- Tree flow (HfApi.list_repo_files) ---
TREE_MATRIX = [
    pytest.param("200_ok",                "success",                  id="200-ok"),
    pytest.param("307_canonical_redirect","success",                  id="307-canonical-redirect"),
    pytest.param("404_entry_not_found",   "EntryNotFoundError",       id="404-entry-not-found-PROPAGATE"),
    pytest.param("404_revision_not_found","RevisionNotFoundError",    id="404-revision-not-found-PROPAGATE"),
    pytest.param("disabled",              "DisabledRepoError",        id="disabled-PROPAGATE"),
    pytest.param("404_repo_not_found",    "RepositoryNotFoundError",  id="404-repo-not-found-aggregate"),
    pytest.param("401_gated",             "GatedRepoError",           id="401-gated-aggregate"),
    pytest.param("403_gated",             "GatedRepoError",           id="403-gated-aggregate"),
    pytest.param("401_bare_anti_enum",    "RepositoryNotFoundError",  id="401-bare-anti-enum-aggregate"),
    pytest.param("401_bare_invalid_creds","RepositoryNotFoundError",  id="401-bare-invalid-creds-aggregate"),
    pytest.param("403_bare",              "HfHubHTTPError",           id="403-bare-aggregate"),
    pytest.param("404_bare",              "RepositoryNotFoundError",  id="404-bare-aggregate-scope-repo"),
    pytest.param("503",                   "HfHubHTTPError",           id="503-aggregate-502"),
]


@pytest.mark.parametrize("scenario,expected", TREE_MATRIX)
def test_tree_matrix_via_hf_api_list_repo_files(
    scenario, expected,
    live_server_url, hf_api_token, configure_fallback,
):
    """Drive ``HfApi.list_repo_files`` against khub for every matrix row."""
    _maybe_skip_disabled(expected)
    configure_fallback(scenario)
    api = HfApi(endpoint=live_server_url, token=hf_api_token)

    def _run():
        return api.list_repo_files("owner/scenario-repo")

    if expected == "success":
        files = asyncio.run(asyncio.to_thread(_run))
        expected_files = [it["path"] for it in OK_TREE_JSON if it["type"] == "file"]
        assert sorted(files) == sorted(expected_files)
    else:
        Exc = _hf_error(expected)
        with pytest.raises(Exc):
            asyncio.run(asyncio.to_thread(_run))


# --- paths-info flow (HfApi.get_paths_info) ---
#
# get_paths_info is a per-file probe; its scope on aggregate is
# "file" → bare 404 → EntryNotFound (parallel to resolve, NOT to
# tree/info).
PATHS_INFO_MATRIX = [
    pytest.param("200_ok",                "success",                  id="200-ok"),
    pytest.param("307_canonical_redirect","success",                  id="307-canonical-redirect"),
    pytest.param("404_entry_not_found",   "EntryNotFoundError",       id="404-entry-not-found-PROPAGATE"),
    pytest.param("404_revision_not_found","RevisionNotFoundError",    id="404-revision-not-found-PROPAGATE"),
    pytest.param("disabled",              "DisabledRepoError",        id="disabled-PROPAGATE"),
    pytest.param("404_repo_not_found",    "RepositoryNotFoundError",  id="404-repo-not-found-aggregate"),
    pytest.param("401_gated",             "GatedRepoError",           id="401-gated-aggregate"),
    pytest.param("403_gated",             "GatedRepoError",           id="403-gated-aggregate"),
    pytest.param("401_bare_anti_enum",    "RepositoryNotFoundError",  id="401-bare-anti-enum-aggregate"),
    pytest.param("401_bare_invalid_creds","RepositoryNotFoundError",  id="401-bare-invalid-creds-aggregate"),
    pytest.param("403_bare",              "HfHubHTTPError",           id="403-bare-aggregate"),
    pytest.param("404_bare",              "EntryNotFoundError",       id="404-bare-aggregate-scope-file"),
    pytest.param("503",                   "HfHubHTTPError",           id="503-aggregate-502"),
]


@pytest.mark.parametrize("scenario,expected", PATHS_INFO_MATRIX)
def test_paths_info_matrix_via_hf_api_get_paths_info(
    scenario, expected,
    live_server_url, hf_api_token, configure_fallback,
):
    """Drive ``HfApi.get_paths_info`` against khub for every matrix row.

    ``get_paths_info`` is a POST to ``/api/{type}s/.../paths-info/{rev}``
    and returns a list of ``RepoFile`` / ``RepoFolder`` dataclasses on
    success. Older hf_hub versions used ``HfApi.paths_info`` as the
    method name, so the test branches on attribute presence.
    """
    _maybe_skip_disabled(expected)
    configure_fallback(scenario)
    api = HfApi(endpoint=live_server_url, token=hf_api_token)

    method = getattr(api, "get_paths_info", None) or getattr(api, "paths_info", None)
    if method is None:
        pytest.skip("HfApi has no get_paths_info / paths_info on this version")

    def _run():
        return method(repo_id="owner/scenario-repo", paths=["config.json"])

    if expected == "success":
        result = asyncio.run(asyncio.to_thread(_run))
        # The returned dataclasses carry a `path` attribute; just
        # confirm we got back at least one entry shaped like our
        # OK_PATHS_INFO_JSON fixture.
        assert len(list(result)) >= 1
    else:
        Exc = _hf_error(expected)
        with pytest.raises(Exc):
            asyncio.run(asyncio.to_thread(_run))
